load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "ChatMessageMediaBubbleContentNode",
    module_name = "ChatMessageMediaBubbleContentNode",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    copts = [
        "-warnings-as-errors",
    ],
    deps = [
        "//submodules/AsyncDisplayKit",
        "//submodules/Display",
        "//submodules/SSignalKit/SwiftSignalKit",
        "//submodules/Postbox",
        "//submodules/IosappCore",
        "//submodules/IosappUIPreferences",
        "//submodules/IosappPresentationData",
        "//submodules/AccountContext",
        "//submodules/GridMessageSelectionNode",
        "//submodules/IosappUI/Components/ChatControllerInteraction",
        "//submodules/IosappUI/Components/Chat/ChatMessageDateAndStatusNode",
        "//submodules/IosappUI/Components/Chat/ChatMessageBubbleContentNode",
        "//submodules/IosappUI/Components/Chat/ChatMessageItemCommon",
        "//submodules/IosappUI/Components/Chat/ChatMessageInteractiveMediaNode",
        "//submodules/IosappUniversalVideoContent",
    ],
    visibility = [
        "//visibility:public",
    ],
)
