load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "ChatMessagePollBubbleContentNode",
    module_name = "ChatMessagePollBubbleContentNode",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    copts = [
        "-warnings-as-errors",
    ],
    deps = [
        "//submodules/AsyncDisplayKit",
        "//submodules/Crc32",
        "//submodules/Display",
        "//submodules/IosappCore",
        "//submodules/Postbox",
        "//submodules/TextFormat",
        "//submodules/UrlEscaping",
        "//submodules/SSignalKit/SwiftSignalKit",
        "//submodules/AccountContext",
        "//submodules/AvatarNode",
        "//submodules/IosappPresentationData",
        "//submodules/ChatMessageBackground",
        "//submodules/IosappUI/Components/Chat/ChatMessageDateAndStatusNode",
        "//submodules/IosappUI/Components/Chat/ChatMessageBubbleContentNode",
        "//submodules/IosappUI/Components/Chat/ChatMessageItemCommon",
        "//submodules/IosappUI/Components/Chat/PollBubbleTimerNode",
        "//submodules/IosappUI/Components/Chat/MergedAvatarsNode",
        "//submodules/IosappUI/Components/Chat/ChatMessageAttachedContentNode",
        "//submodules/IosappUI/Components/TextNodeWithEntities",
        "//submodules/IosappUI/Components/Chat/ShimmeringLinkNode",
        "//submodules/IosappUI/Components/EmojiTextAttachmentView",
        "//submodules/PhotoResources",
        "//submodules/LocationResources",
        "//submodules/IosappUI/Components/ChatControllerInteraction",
        "//submodules/RadialStatusNode",
        "//submodules/IosappUI/Components/ComposePollScreen",
    ],
    visibility = [
        "//visibility:public",
    ],
)
