load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "ChatFolderLinkPreviewScreen",
    module_name = "ChatFolderLinkPreviewScreen",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    copts = [
        "-warnings-as-errors",
    ],
    deps = [
        "//submodules/AsyncDisplayKit",
        "//submodules/Display",
        "//submodules/Postbox",
        "//submodules/IosappCore",
        "//submodules/SSignalKit/SwiftSignalKit",
        "//submodules/ComponentFlow",
        "//submodules/Components/ViewControllerComponent",
        "//submodules/Components/ComponentDisplayAdapters",
        "//submodules/Components/MultilineTextComponent",
        "//submodules/IosappPresentationData",
        "//submodules/AccountContext",
        "//submodules/AppBundle",
        "//submodules/IosappStringFormatting",
        "//submodules/PresentationDataUtils",
        "//submodules/Components/SolidRoundedButtonComponent",
        "//submodules/IosappUI/Components/ButtonComponent",
        "//submodules/IosappUI/Components/PlainButtonComponent",
        "//submodules/IosappUI/Components/AnimatedCounterComponent",
        "//submodules/AvatarNode",
        "//submodules/CheckNode",
        "//submodules/Markdown",
        "//submodules/UndoUI",
        "//submodules/PremiumUI",
        "//submodules/QrCodeUI",
        "//submodules/InviteLinksUI",
        "//submodules/Components/MultilineTextWithEntitiesComponent",
    ],
    visibility = [
        "//visibility:public",
    ],
)
